//На прямую не редактировать Сгенерировано через скрипт generate-icons 

 export const names = [
  "align-justify-svgrepo-com",
  "circle-check-svgrepo-com",
  "circle-pause-svgrepo-com",
  "clapperboard-play-svgrepo-com",
  "clock-eight-svgrepo-com",
  "cloud-arrow-down-svgrepo-com",
  "cloud-music-svgrepo-com",
  "clouds-svgrepo-com",
  "cookie-svgrepo-com",
  "credit-card-alt-svgrepo-com",
  "crown-svgrepo-com",
  "dialpad-circle-svgrepo-com",
  "droplet-alt-svgrepo-com",
  "expand-wide-svgrepo-com",
  "face-frown-svgrepo-com",
  "face-smile-svgrepo-com",
  "file-check-svgrepo-com",
  "file-exclamation-svgrepo-com",
  "fingerprint-alt-svgrepo-com",
  "globe-svgrepo-com",
  "heart-svgrepo-com",
  "hexagon-svgrepo-com",
  "id-card-svgrepo-com",
  "list-svgrepo-com",
  "location-pin-alt-1-svgrepo-com",
  "lock-alt-svgrepo-com",
  "map-location-pin-svgrepo-com",
  "palette-svgrepo-com",
  "shield-alt-svgrepo-com",
  "shield-dollar-svgrepo-com",
  "skull-alt-svgrepo-com",
  "sliders-svgrepo-com",
  "snow-alt-svgrepo-com",
  "temperature-half-svgrepo-com",
  "tenge-sign-svgrepo-com",
  "text-svgrepo-com",
  "umbrella-svgrepo-com",
  "user-check-alt-1-svgrepo-com",
  "video-svgrepo-com"
] as const